from PyQt5.QtWidgets import*
app = QApplication([])
main_win = QWidget()
main_win.resize(700,500)
main_win.setWindowTitle("Порожнє вікно")
lb_image=QLabel("Картинка")
btn_dir=QPushButton("Папка")
lw_files=QListWidget()
btn_left=QPushButton("Вліво")
btn_right=QPushButton("Вправо")
btn_flip=QPushButton("Дзеркало")
btn_sharp=QPushButton("Рікість")
btn_bw=QPushButton("Ч/Б")
row=QHBoxLayout()
col1=QVBoxLayout()
col2=QVBoxLayout()
col1.addWidget(btn_dir)
col2.addWidget(lb_image,95)
row_tools=QHBoxLayout()
row_tools.addWidget(btn_left)
row_tools.addWidget(btn_right)
row_tools.addWidget(btn_flip)
row_tools.addWidget(btn_sharp)
row_tools.addWidget(btn_bw)
col2.addLayout(row_tools)
row.addLayout(col1,20)
row.addLayout(col2,80)
main_win.setLayout(row)
workdir=""
def chooseworkdir():
    global workdir
    workdir=QFileDialog.getExistingDirectory()
main_win.show()
app.exec_()
